### ISSUE TITLE
Auto complete not poping up

### ISSUE THREAD

**Issue by sannamalai76** [svipas/vscode-code-autocomplete#1]
- OS version: Windows 10
- VS Code version: Visual Studio code insiders
- Programming language: javascript and typescript
- Extension version: 1.1.0

#### TabNine logs

Run from Command Palette: `TabNine: config`, the logs are located at the bottom of the page.

#### VS Code console logs

[2020-07-07][23:53:46][server][DEBUG] [autocomplete] 2 ms
[2020-07-07][23:53:46][lunar_transport::client][INFO] Searching for completions with prefix "st"
[2020-07-07][23:53:46][server][DEBUG] [autocomplete] 2 ms

Run from Command Palette: `Developer: Toggle Developer Tools`.

### Issue details
i tried to follow this example but suggestions were not poping up

st

/**
 * Concatenate two strings
 * @param a the first string to concatenate
 * @param b the second string to concatenate
 * @return the concatenated string
 */

**Comment by svipas** [comment]
As I can see you have TabNine binary installed, if auto-complete doesn't popup this could be TabNine problems because auto-complete works with this extension if nothing was modified.

At first launch it can delay auto-complete because it reads your project, etc. But after 1 minute it should give you suggestions.

Check status bar TabNine if it contains clock it means request was timed out so you can increase it by modifying VS Code settings and restarting/reloading VS Code.

```
	// Timeout in milliseconds after which TabNine request is terminated. Restart required.
	"tabnine.requestTimeout": 50,
```
