### ISSUE TITLE
how to only show the suggestion thats going to be inserted ?

### ISSUE THREAD

**Issue by ctf0** [svipas/vscode-code-autocomplete#3]
atm the suggestion will show extra information which wont be wont be inserted on selection, i believe its related to
> Included postfix in suggestions for e.g. instead of log( it will show log().

**Comment by svipas** [comment]
I'm not sure I understand what you mean, could you please elaborate with code examples, etc.?

In official TabNine extension in autocomplete you will see `log(`, but actually it inserts `log()`, I added that postfix in suggestions list so instead of `log(` you will see `log()` which is actual input.

**Comment by ctf0** [comment]
sometimes the suggestion will be something like `$var->` but the inserted text with be `->` so how to show what will be actually inserted instead of just a context ?

**Comment by svipas** [comment]
Could you please record the video or show me images of before/after completion with suggestion list? I prefer videos other images since they give more context, but it's up to you. Thanks!

**Comment by ctf0** [comment]
will do.

**Comment by ctf0** [comment]
**update**

it was cuzed by another version, sorry for the inconvenience

**Comment by svipas** [comment]
No problem 😊
